### ISSUE TITLE
Get backlinks on adapter apps not stack page.

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang.com#15]
Until know we tried to get backlinks for the stack pages. I want to challenge this.
It's harder to get backlinks on `/c/nextjs` than on `/m/adapter`. Because products sell better then inlang curated pages.

Stackpages don't match the search intend when I google `svelte-i18n` -> I want to get the the adapter.

How I got the insight:

[https://www.loom.com/share/71a5b638441b4c76926a28a1457f075b](https://www.loom.com/share/71a5b638441b4c76926a28a1457f075b)

@loris.sigrist do you agree that we want to put more effort in these pages then on the stack pages?

If yes let's collect actions in the issue.

**Comment by LorisSigrist** [comment]
I 100% agree that we should push people to the adapter pages directly. It's one less step to get started & reduces indirection

**Comment by NilsJacobsen** [comment]
@loris.sigrist gonna plan further here [https://docs.google.com/document/d/13VoXKLACDo1KdC_GTpqNueNEZdrLpwxsYuodqa2TCcs/edit?usp=sharing](https://docs.google.com/document/d/13VoXKLACDo1KdC_GTpqNueNEZdrLpwxsYuodqa2TCcs/edit?usp=sharing)

**Comment by NilsJacobsen** [comment]
After call with @loris.sigrist 

#### Next steps:

* Make adapter links more prominent [INWEB-33](https://linear.app/opral/issue/INWEB-33/move-the-adapter-page-links-to-the-top-on-paraglidejs-page)
* Optimize for SEO [INWEB-32](https://linear.app/opral/issue/INWEB-32/optimize-content-on-adapter-pages) [INWEB-31](https://linear.app/opral/issue/INWEB-31/optimize-slugs-for-adapter-pages)

**Comment by NilsJacobsen** [comment]
Small win:<br>First people are coming from the new links on google:

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/0b09ccb0-4b5a-4f90-a511-7edc200c06f4/e7f3fd54-9529-4c85-8259-41689e29ed21?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wYjA5Y2NiMC00YjVhLTRmOTAtYTUxMS03ZWRjMjAwYzA2ZjQvZTdmM2ZkNTQtOTUyOS00Yzg1LTgyNTktNDE2ODllMjllZDIxIiwiaWF0IjoxNzEzMTkxNTI1LCJleHAiOjMzMjgzNzUxNTI1fQ.gRV8KKHKq0jHUqn7g-H89CGYNwxWWN4SeKle4fDiRsw " alt="image.png" width="689" height="129" />

**Comment by NilsJacobsen** [comment]
@loris.sigrist, can we close this as we are following the right initiatives to fulfill this?

**Comment by LorisSigrist** [comment]
Go ahead!
