### ISSUE TITLE
Optimize slugs for adapter pages

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang.com#18]
We should stop thinking about slug as a derivate of paraglide. They should be stand-alone. With that in mind it makes sense to optimize the slugs.

### Approach

We want to rank for: 

* next i18n 
* svelte i18n
* And similar …

Google can't make the connection:
next i18n -> library-inlang-paraglideJsAdapterNextJs (resulting in no ranking at all)

### Proposal

* remove "library-inlang"
* Add "i18n"
* remove "adapter"

\-> something like paraglide-next-i18n

**Comment by NiklasBuchfink** [comment]
This makes sense, aligns with the users search intent and is a known pattern from i18next 👍🏻

**Comment by NilsJacobsen** [comment]
@loris.sigrist are you fine with this initial naming convention?
`paraglide-{stack}-i18n` for the slugs?

**Comment by samuelstroschein** [comment]
only the website "slug"?

**Comment by LorisSigrist** [comment]
correct

**Comment by NilsJacobsen** [comment]
@loris.sigrist I put you in review
