### ISSUE TITLE
Move the adapter page links to the top on ParaglideJS page

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang.com#20]
* People have trouble finding the adapter pages

**Comment by NiklasBuchfink** [comment]
I like that, if a user enters the ParaglideJS page, the most important thing is to funnel them to the correct adapter. It makes sense to place the "decision tree" at the top.
I don't have anything specific in mind, but this concept could also apply to other pages with the aim of improving user guidance.

**Comment by NilsJacobsen** [comment]
@loris.sigrist can we close this?

**Comment by LorisSigrist** [comment]
Yes
