### ISSUE TITLE
How should product pages be?

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang.com#21]
@felix.haeberle @loris.sigrist @niklas.buchfink

Let's collect requirements for the product landing pages V2.

* What content do you want to show?
* What should be the info architecture?

**Goal -> speccing**

Example:

```
- Landingpage (more like html)
- Docs (more like md)
- Changelog (generated)
```

**Comment by LorisSigrist** [comment]
A more customizable Landing-page is very welcome! 

> What content do you want to show?

* on the landing page: 
  * Still mostly text and images, but in more interesting layouts. Right now the paraglide adapter pages are using a hack for multiple columns & stuff by just showing an image. Stuff like that should be possible with real HTML
  * If we're getting crazy, an interactive editor where you can type in a message & see a realtime compiled version of that message
  * Convince people to go to the docs page
* on the docs pages
  * Markdown, ideally multiple pages
* Changelogs can stay the same

> What should be the info architecture?

I expect most apps will follow
Landingpage-Pitch -> Minimal Getting Started -> Advanced Configuration

**Comment by NilsJacobsen** [comment]
@niklas.buchfink what sections would you want to show on the landing page, which on the docs?

**Comment by NilsJacobsen** [comment]
@loris.sigrist paraglide is probably a special one -> [INWEB-35](https://linear.app/opral/issue/INWEB-35/how-do-we-treat-paraglide-main-page)

**Comment by NilsJacobsen** [comment]
> Landingpage-Pitch -> Minimal Getting Started -> Advanced Configuration

The gettings started is only needed for paraglide i guess?

**Comment by felixhaeberle** [comment]
@nils.jacobsen 

I have likely the same requirements like Loris. For me:

> What content do you want to show?

* "Structuring options" in form of pages would help a lot
* Layouts in form of Columns with responsive behavior
* Some custom elements which are supported:
  * Dialog/Collapsible (FAQ etc.)
  * StackBlitz / some sort of playground rendering support (Code examples)

> What should be the info architecture?

* `MARKETPLACE.md(x)` as main entry point = landing page
  which is embedded in the marketplace and the marketplace additionally renders docs in a navigation bar like:

—
some kind of universal structure 

* Getting started (`/docs/getting-started.mdx`)
* Advanced Config (`/docs/advanced-config.mdx`)
* Feature Docs (`/docs/feat-1/shiny-feat.mdx`)

For this approach, it could be beneficial if we then have a structural document like some sort of `tableOfContent.json` to get us Directory/Hierachy names. We can also use FrontMatter for meta information on pages itself.  

>

**Comment by NiklasBuchfink** [comment]
[INWEB-34](https://linear.app/opral/issue/INWEB-34/how-should-product-pages-be#comment-551c1e06) @nils.jacobsen Similar to the others
Landing page:

* responsive grid or gallery
* playable video like we already did for Ninja
* of course, I don't need the doc sidebar navigation for this page

Docs:

* Accordions/Collapsables – FAQ
* Multipage docs – used to adjust stories for different personas and use cases

A way to link to help & resources:

* Twitter
* Discord channel
* Bug tracker
* Feature requests
* Feedback

I want a place for all these links somewhere on my product page. My solution in-app was the Question mark similar to Figma and Linear:

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/e99255e0-45a4-40ee-837c-c394ab25888f/78f6870d-eaec-49bd-af95-37a1f2281867?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9lOTkyNTVlMC00NWE0LTQwZWUtODM3Yy1jMzk0YWIyNTg4OGYvNzhmNjg3MGQtZWFlYy00OWJkLWFmOTUtMzdhMWYyMjgxODY3IiwiaWF0IjoxNzEyMTYwNDE3LCJleHAiOjMzMjgyNzIwNDE3fQ.45iGkBMHulhGFGx1u6bgLfhc_TRQHckv0lq_Q9yR76w " alt="image.png" width="490" height="850" />

**Comment by LorisSigrist** [comment]
Another thing that would be really nice for authoring is the ability to use local images without needing to go through JsDelivr. With the more complex layouts on the landing page we will be using way more images

**Comment by felixhaeberle** [comment]
@LorisSigrist Thats also what I proposed with "Media Serving" above 👏👍
