### ISSUE TITLE
Update or deprecate `manage.inlang.com`

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/inlang.com#35]
### Context

* Install, Uninstall & Edit language tags is broken in manage<br>(Console error: `add` does not exists on repo)
* After [FINK-21](https://linear.app/opral/issue/FINK-21/introduce-inlang-settings-to-fink) is merged basic project settings are introduced in Fink

### Proposal

Option:

1. We deprecate manage + introduce install and uninstall via settings soon
2. We will fix the issues and keep manage alive until we introduce this feature in the settings components

**Comment by NilsJacobsen** [comment]
Good point, didn't know we have issues there. We definitely need testing for the settings component.<br><br>We have around 330 users on manage each month. Which is a decent number. As we need some week, maybe month for getting module management in the settings component out of the door, we should probably fix it.
