### ISSUE TITLE
Use front matter to set page based information for rendering and seo

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang.com#41]
* title, description, image … needs to be set per page 
* We can handle that with frontmatter

**Comment by NilsJacobsen** [comment]
**Update:**

* I added frontmatter to markdown
* You can define page title and meta description for now
* I added a Schema that checks for correctness -> if frontmatter is defined, it needs to be correct otherwise, throw error

```
const MarkdownFrontmatter = Type.Object({
		title: Type.String(),
		description: Type.String(),
	})
```

@samuel.stroschein I would add this type to versioned interfaces, wha do you think?

**Comment by NilsJacobsen** [comment]
Well that is true, then I keep it in the package.

> can't use "use"

?

**Comment by samuelstroschein** [comment]
markdown can't import typescript
