### ISSUE TITLE
Rendering issue on the website

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang.com#50]
Related to routing. I'm on it.

**Comment by NilsJacobsen** [comment]
Can now reproduce it locally in production.

**Comment by NilsJacobsen** [comment]
Made a rollback. So current site is not with errors.

**Comment by samuelstroschein** [comment]
@nils.jacobsen maybe good to deploy the website with versions too instead of pushing from main

**Comment by NilsJacobsen** [comment]
Well we could do that, but I'm currently working with PRs, that were green. But I didn't do a local production check.

**Comment by NilsJacobsen** [comment]
Found the problem. Gonna work on a fix.

**Comment by NilsJacobsen** [comment]
Should be fixed ✅
