### ISSUE TITLE
remove third party libraries

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang.com#86]
**Context**

Third party libraries on inlang.com that are advertised as apps led to recurring confusion. 

**Proposal**

Remove all third party libraries (apps). Plugins for third party libraries fill the gap and are actually useful.  

@samuel.stroschein said in [INWEB-107](https://linear.app/opral/issue/INWEB-107/re-add-vue-i18n-to-marketplace-overview-page#comment-6a94ea3e):

> @nils.jacobsen hopped on a call with @felix.haeberle: felix agreed to build plugins.

**Comment by NilsJacobsen** [comment]
They are already not listed. In theory they are still there but you can't find them, just for SEO.

**Comment by samuelstroschein** [comment]
SEO is negatively impacted. users don't know what to do on those pages. Library specific plugins have better SEO.

**Comment by NilsJacobsen** [comment]
Did some quick research:

* We can remove it
* We should make proper 301 redirects to the correct plugins

Good resource -> [https://www.quora.com/Why-is-it-recommended-not-to-remove-pages-from-your-website](https://www.quora.com/Why-is-it-recommended-not-to-remove-pages-from-your-website)
