### ISSUE TITLE
Double navigation on the docs page

### ISSUE THREAD

**Issue by jannesblobel** [opral/inlang.com#88]
### Context

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/a5342fb9-2b85-4c80-b2db-cd5f19b989c5/9467791a-406b-442f-ae80-54b27bcba48b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9hNTM0MmZiOS0yYjg1LTRjODAtYjJkYi1jZDVmMTliOTg5YzUvOTQ2Nzc5MWEtNDA2Yi00NDJmLWFlODAtNTRiMjdiY2JhNDhiIiwiaWF0IjoxNzE3NzY1MTg3LCJleHAiOjMzMjg4MzI1MTg3fQ.y_nQTHfOH_p2j7Zzxm6QFmo7iWWgFAXFuL0SwL4cr3M " alt="CleanShot 2024-06-07 at 14.40.06@2x.png" width="1592" height="1310" />

There are too many navigation options for the same pages.

### Proposal

Adapt the navigation as on the marketplace pages

**Comment by samuelstroschein** [comment]
@jannes.blobel this seems so minor. and i do see value in having plugins under "ecosystem" concepts. 

people are clicking on both

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/a610125d-2131-4844-9abc-2bbb433d7504/1f453c12-bf8d-4adb-9ca9-bbbcb552f0e4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9hNjEwMTI1ZC0yMTMxLTQ4NDQtOWFiYy0yYmJiNDMzZDc1MDQvMWY0NTNjMTItYmY4ZC00YWRiLTljYTktYmJiY2I1NTJmMGU0IiwiaWF0IjoxNzE3NzcxOTc4LCJleHAiOjMzMjg4MzMxOTc4fQ.JTpPmFoGrzIUJot4l-DWiWob6wiIVx43FIFzeqqJ_LU " alt="CleanShot 2024-06-07 at 10.51.39@2x.png" width="1420" height="1092" />

**Comment by jannesblobel** [comment]
I also clicked on both because I wanted to know the difference, but Nils can simply decide what he wants to do with it.

**Comment by NilsJacobsen** [comment]
I think the problem this approach is solving was:

* We need different entrypoints for different usecases to be shown as separate docs pages on the top nav
* Plugins and Lintrules are also a concept of ecosystem so, it needs to go on the subnavigation to. 

I was quite happy with the arrows, cause it shows that you leave the page. We also have that in the new product pages. <br><br>-> I think we gonna leave it like that for now.
